services:
  - type: web
    name: collabsphere-backend
    runtime: node
    region: singapore
    rootDir: server
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: NODE_VERSION
        value: 20
      - key: NODE_ENV
        value: production
